modLoader="javafml"
loaderVersion="*"
license="MIT"

[[mods]]
modId="tradechoice"
version="${version}"
displayName="Trade Choice"
description="Mark desired villager trades and get audio alerts when they appear. Optional: install the Trade Cycling mod for auto-search."

[[mixins]]
config = "tradechoice.client.mixins.json"

[[dependencies.tradechoice]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0.0-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tradechoice]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,26.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tradechoice]]
    modId="trade_cycling"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="CLIENT"
